baseurl: /blog
# Site settings
description: yeshiyuan's blog
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "http://www.yeshiyuan.com" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: yeshiyuan
user_description: 叶仕苑的博客
user_title: yeshiyuan's blog
email: yeshiyuan00@gmail.com
twitter_username: yeshiyuan
github_username:  yeshiyuan
gplus_username:  yeshiyuan
disqus_username: yeshiyuan

# Build settings
markdown: kramdown
highlighter: pygments
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Series
    url: /series
  - title: Tags
    url: /tags
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
